// grafana config
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://github.com/jubril-adeyi/terraforom-k8s-webapp-sockshop.git
    targetRevision: HEAD
    ref: jubril-adeyi
  - repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 6.52.2
    helm:
      valueFiles:
        - $jubril-adeyi/argocd-apps/values/grafana.yaml         
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
