apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.9.1
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
    chart: cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    
