apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: argo-cd
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: jbadeyi@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - http01:
          ingress:
            class: nginx
